development:
  enable: true
  default:
    queue: warren
    warren:
      - host: localhost 
        port: 5672
      - host: localhost 
        port: 5673
test:
  default:
    queue: rabbit
    host: localhost 
    port: 5672
  enable: true
production:
  default:
    queue: rabbit
    host: localhost 
    port: 5672
  enable: true
